import 'package:hive/hive.dart';

part 'podcast_models.g.dart'; // This will be generated by build_runner

// User Model
@HiveType(typeId: 0)
class UserProfile extends HiveObject {
  @HiveField(0)
  String uid;

  @HiveField(1)
  String email;

  @HiveField(2)
  String displayName;

  @HiveField(3)
  String? photoUrl;

  @HiveField(4)
  String preferredLanguage;

  @HiveField(5)
  DateTime createdAt;

  @HiveField(6)
  DateTime lastSeen;

  UserProfile({
    required this.uid,
    required this.email,
    required this.displayName,
    this.photoUrl,
    this.preferredLanguage = 'en',
    required this.createdAt,
    required this.lastSeen,
  });

  factory UserProfile.fromJson(Map<String, dynamic> json) {
    return UserProfile(
      uid: json['uid'] ?? '',
      email: json['email'] ?? '',
      displayName: json['displayName'] ?? '',
      photoUrl: json['photoUrl'],
      preferredLanguage: json['preferredLanguage'] ?? 'en',
      createdAt: DateTime.parse(json['createdAt']),
      lastSeen: DateTime.parse(json['lastSeen']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'uid': uid,
      'email': email,
      'displayName': displayName,
      'photoUrl': photoUrl,
      'preferredLanguage': preferredLanguage,
      'createdAt': createdAt.toIso8601String(),
      'lastSeen': lastSeen.toIso8601String(),
    };
  }
}

// Podcast Model
@HiveType(typeId: 1)
class Podcast extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String description;

  @HiveField(3)
  String imageUrl;

  @HiveField(11)
  String thumbnailUrl;

  @HiveField(4)
  String publisher;

  @HiveField(5)
  String language;

  @HiveField(6)
  List<String> genres;

  @HiveField(7)
  int totalEpisodes;

  @HiveField(8)
  String? website;

  @HiveField(9)
  bool isUserUploaded;

  @HiveField(10)
  String? uploadedByUserId;

  Podcast({
    required this.id,
    required this.title,
    required this.description,
    required this.imageUrl,
    required this.thumbnailUrl,
    required this.publisher,
    required this.language,
    required this.genres,
    required this.totalEpisodes,
    this.website,
    this.isUserUploaded = false,
    this.uploadedByUserId,
  });

  factory Podcast.fromJson(Map<String, dynamic> json) {
    return Podcast(
      id: json['id']?.toString() ?? '',
      title: json['title']?.toString() ?? 'Untitled Podcast',
      description: json['description']?.toString() ?? '',
      imageUrl: json['image']?.toString() ?? '',
      thumbnailUrl: json['thumbnail']?.toString() ?? json['image']?.toString() ?? '',
      publisher: json['publisher']?.toString() ?? 'Unknown Publisher',
      language: json['language']?.toString() ?? 'en',

      // ListenNotes gives genre_ids, not "genres"
      genres: (json['genre_ids'] != null)
          ? List<int>.from(json['genre_ids']).map((e) => e.toString()).toList()
          : [],

      totalEpisodes: json['total_episodes'] ?? 0,
      website: json['website']?.toString(),
      isUserUploaded: json['isUserUploaded'] ?? false,
      uploadedByUserId: json['uploadedByUserId'],
    );
  }


  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'imageUrl': imageUrl,
      'thumbnailUrl': thumbnailUrl,
      'publisher': publisher,
      'language': language,
      'genres': genres,
      'total_episodes': totalEpisodes,
      'website': website,
      'isUserUploaded': isUserUploaded,
      'uploadedByUserId': uploadedByUserId,
    };
  }
}

// Episode Model
@HiveType(typeId: 2)
class Episode extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String title;

  @HiveField(2)
  String description;

  @HiveField(3)
  String audioUrl;

  @HiveField(4)
  String imageUrl;

  @HiveField(5)
  int audioLengthSec;

  @HiveField(6)
  DateTime pubDateMs;

  @HiveField(7)
  String podcastId;

  @HiveField(8)
  bool isUserUploaded;

  Episode({
    required this.id,
    required this.title,
    required this.description,
    required this.audioUrl,
    required this.imageUrl,
    required this.audioLengthSec,
    required this.pubDateMs,
    required this.podcastId,
    this.isUserUploaded = false,
  });

  factory Episode.fromJson(Map<String, dynamic> json) {
    return Episode(
      id: json['id']?.toString() ?? '',
      title: json['title']?.toString() ?? '',
      description: json['description']?.toString() ?? '',
      audioUrl: json['audio']?.toString() ?? '',
      imageUrl: json['image']?.toString() ?? '',
      audioLengthSec: json['audio_length_sec'] ?? 0,
      pubDateMs: DateTime.fromMillisecondsSinceEpoch(
        json['pub_date_ms'] ?? (json['pub_date'] ?? 0),
      ),
      podcastId: json['podcast_id']?.toString() ?? '',
      isUserUploaded: json['isUserUploaded'] ?? false,
    );
  }


  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'audioUrl': audioUrl,
      'imageUrl': imageUrl,
      'audio_length_sec': audioLengthSec,
      'pub_date_ms': pubDateMs.millisecondsSinceEpoch,
      'podcastId': podcastId,
      'isUserUploaded': isUserUploaded,
    };
  }

  String get formattedDuration {
    final hours = audioLengthSec ~/ 3600;
    final minutes = (audioLengthSec % 3600) ~/ 60;
    final seconds = audioLengthSec % 60;

    if (hours > 0) {
      return '${hours}h ${minutes}m ${seconds}s';
    } else if (minutes > 0) {
      return '${minutes}m ${seconds}s';
    } else {
      return '${seconds}s';
    }
  }
}

// Listening Progress Model
@HiveType(typeId: 3)
class ListeningProgress extends HiveObject {
  @HiveField(0)
  String episodeId;

  @HiveField(1)
  String userId;

  @HiveField(2)
  int positionMs;

  @HiveField(3)
  int durationMs;

  @HiveField(4)
  DateTime lastListened;

  @HiveField(5)
  bool isCompleted;

  ListeningProgress({
    required this.episodeId,
    required this.userId,
    required this.positionMs,
    required this.durationMs,
    required this.lastListened,
    this.isCompleted = false,
  });

  double get progressPercentage {
    if (durationMs == 0) return 0.0;
    return (positionMs / durationMs).clamp(0.0, 1.0);
  }

  factory ListeningProgress.fromJson(Map<String, dynamic> json) {
    return ListeningProgress(
      episodeId: json['episodeId'] ?? '',
      userId: json['userId'] ?? '',
      positionMs: json['positionMs'] ?? 0,
      durationMs: json['durationMs'] ?? 0,
      lastListened: DateTime.parse(json['lastListened']),
      isCompleted: json['isCompleted'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'episodeId': episodeId,
      'userId': userId,
      'positionMs': positionMs,
      'durationMs': durationMs,
      'lastListened': lastListened.toIso8601String(),
      'isCompleted': isCompleted,
    };
  }
}

// Favorite Model
@HiveType(typeId: 4)
class Favorite extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String userId;

  @HiveField(2)
  String itemId; // Can be podcast or episode ID

  @HiveField(3)
  String itemType; // 'podcast' or 'episode'

  @HiveField(4)
  DateTime addedAt;

  Favorite({
    required this.id,
    required this.userId,
    required this.itemId,
    required this.itemType,
    required this.addedAt,
  });

  factory Favorite.fromJson(Map<String, dynamic> json) {
    return Favorite(
      id: json['id'] ?? '',
      userId: json['userId'] ?? '',
      itemId: json['itemId'] ?? '',
      itemType: json['itemType'] ?? '',
      addedAt: DateTime.parse(json['addedAt']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'itemId': itemId,
      'itemType': itemType,
      'addedAt': addedAt.toIso8601String(),
    };
  }
}

// Listening Stats Model
@HiveType(typeId: 5)
class ListeningStats extends HiveObject {
  @HiveField(0)
  String userId;

  @HiveField(1)
  int totalListeningTimeMs;

  @HiveField(2)
  int episodesCompleted;

  @HiveField(3)
  Map<String, int> categoryStats; // category -> listening time in ms

  @HiveField(4)
  Map<String, int> dailyStats; // date -> listening time in ms

  @HiveField(5)
  DateTime lastUpdated;

  ListeningStats({
    required this.userId,
    this.totalListeningTimeMs = 0,
    this.episodesCompleted = 0,
    required this.categoryStats,
    required this.dailyStats,
    required this.lastUpdated,
  });

  String get formattedTotalTime {
    final hours = totalListeningTimeMs ~/ (1000 * 3600);
    final minutes = (totalListeningTimeMs % (1000 * 3600)) ~/ (1000 * 60);

    if (hours > 0) {
      return '${hours}h ${minutes}m';
    } else {
      return '${minutes}m';
    }
  }

  factory ListeningStats.fromJson(Map<String, dynamic> json) {
    return ListeningStats(
      userId: json['userId'] ?? '',
      totalListeningTimeMs: json['totalListeningTimeMs'] ?? 0,
      episodesCompleted: json['episodesCompleted'] ?? 0,
      categoryStats: Map<String, int>.from(json['categoryStats'] ?? {}),
      dailyStats: Map<String, int>.from(json['dailyStats'] ?? {}),
      lastUpdated: DateTime.parse(json['lastUpdated']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'userId': userId,
      'totalListeningTimeMs': totalListeningTimeMs,
      'episodesCompleted': episodesCompleted,
      'categoryStats': categoryStats,
      'dailyStats': dailyStats,
      'lastUpdated': lastUpdated.toIso8601String(),
    };
  }
}

