// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7b22dkZ7R0hLEOw3Ben-Eu3zeQmdjr4',
    appId: '1:570249699188:web:3c306b3881411a78ec9621',
    messagingSenderId: '570249699188',
    projectId: 'podcasttracker',
    authDomain: 'podcasttracker.firebaseapp.com',
    storageBucket: 'podcasttracker.firebasestorage.app',
    measurementId: 'G-Y435VPV00Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkuRn7GsExpcg2HcNOQYmSkLHCdozKCg',
    appId: '1:570249699188:android:8550bdbc4268b6e6ec9621',
    messagingSenderId: '570249699188',
    projectId: 'podcasttracker',
    storageBucket: 'podcasttracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YPdD3clcUgjKcZOnbS6NdIUnkajVzzA',
    appId: '1:570249699188:ios:2396482435315eb1ec9621',
    messagingSenderId: '570249699188',
    projectId: 'podcasttracker',
    storageBucket: 'podcasttracker.firebasestorage.app',
    iosClientId: '570249699188-dcvgoldafbaevu94k3nhboted012m1p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.podcastTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-YPdD3clcUgjKcZOnbS6NdIUnkajVzzA',
    appId: '1:570249699188:ios:2396482435315eb1ec9621',
    messagingSenderId: '570249699188',
    projectId: 'podcasttracker',
    storageBucket: 'podcasttracker.firebasestorage.app',
    iosClientId: '570249699188-dcvgoldafbaevu94k3nhboted012m1p6.apps.googleusercontent.com',
    iosBundleId: 'com.example.podcastTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA7b22dkZ7R0hLEOw3Ben-Eu3zeQmdjr4',
    appId: '1:570249699188:web:91b6f74486225125ec9621',
    messagingSenderId: '570249699188',
    projectId: 'podcasttracker',
    authDomain: 'podcasttracker.firebaseapp.com',
    storageBucket: 'podcasttracker.firebasestorage.app',
    measurementId: 'G-33CZB8EETE',
  );
}
